# Generated by Django 3.0.3 on 2020-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
    ]
