# Generated by Django 3.0.3 on 2020-02-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20200220_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
    ]
