# Generated by Django 3.0.3 on 2020-03-03 10:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_shop_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
