# Generated by Django 3.0.3 on 2020-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20200303_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%M/%D'),
        ),
    ]
