# Generated by Django 3.0.3 on 2020-07-16 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20200716_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 14, 41, 36, 959343)),
        ),
    ]
