# Generated by Django 3.0.3 on 2020-07-17 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20200716_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_with_Aadhar',
            field=models.ImageField(default='../media/aadhar/woman-holding-identification-card-CTYYDW.jpg', upload_to='aadhar/%Y/%M/%D'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 17, 9, 52, 24, 242746)),
        ),
    ]
