# Generated by Django 3.0.3 on 2020-07-18 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_auto_20200717_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 18, 8, 52, 42, 997986)),
        ),
    ]
