# Generated by Django 3.0.3 on 2020-07-18 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_auto_20200718_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 18, 9, 30, 31, 301088)),
        ),
    ]
